spring.application.name=OnlineRadioStation
spring.datasource.url=jdbc:mysql://localhost:3306/onlineradiostation
spring.datasource.username=root
spring.datasource.password=14472281447
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.charset=UTF-8